install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version

script:
  - hugo

deploy:
  local_dir: richdayandnight.github.io
  repo: richdayandnight/richdayandnight.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: tamika.70e15356@tryninja.io
  name: "richdayandnight"
  on:
    branch: master
